spring:
  datasource:
    url: jdbc:mysql://rm-bp16t7i071284ljuo.mysql.rds.aliyuncs.com:3306/bright_apollo?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: Iltwao!1
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: springcloud-provider-obox
  profiles:
    active: test
mybatis:
  type-aliases-package: com.bright.apollo.domain.model
  configuration:
    cache-enabled: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com:
      xiaolyuh: debug
    org:
      springframework:
        web: debug
        transaction: true
      mybatis: debug
server:
  port: 8200
