spring:
  datasource:
    url: jdbc:mysql://192.168.200.200:3306/bright_apollo_user
    username: admin
    password: im123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: springcloud-provider-device
  profiles:
    active: test
mybatis:
  type-aliases-package: com.bright.apollo.domain.model
  mapper-locations: classpath*:/mybaits/*Mapper.xml
  configuration:
    cache-enabled: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com:
      xiaolyuh: debug
    org:
      springframework:
        web: debug
        transaction: true
      mybatis: debug
server:
  port: 8100
